import {
  common_HealthResponse,
  common_SumResponse,
} from '../api-autogenerated';

export const setMockUndefined = (obj: any) => {
  Object.keys(obj).forEach(key => {
    obj[key] = undefined;
  });
  return obj;
};

export const mock_endpointsCommon_HealthResponse: common_HealthResponse = {
  status: 'OK',
};

export const mock_endpointsCommon_SumResponse: common_SumResponse = {
  result: 7,
};
