import {
  go_typescript_react_boilerplate_src_server_endpoints_common_HealthResponse,
  go_typescript_react_boilerplate_src_server_endpoints_common_SumResponse,
} from '../api-autogenerated';

export const setMockUndefined = (obj: any) => {
  Object.keys(obj).forEach(key => {
    obj[key] = undefined;
  });
  return obj;
};

interface IMockEndpointResponses {
  '/api/common/health': {
    get: go_typescript_react_boilerplate_src_server_endpoints_common_HealthResponse;
  };
  '/api/common/sum': {
    post: go_typescript_react_boilerplate_src_server_endpoints_common_SumResponse;
  };
}

export const mockEndpointResponses: IMockEndpointResponses = {
  '/api/common/health': {
    get: {
      status: 'OK',
    },
  },
  '/api/common/sum': {
    post: {
      result: 7,
    },
  },
};
