import { DefaultService } from '../../api-autogenerated';
import generalUtil from '../../utils/generalUtil';

const handleCalculatorClick_Client = (a: number, b: number) => {
  return a + b;
};

const handleCalculatorClick_Server = async (numbers: number[]) => {
  try {
    const returnVal = await DefaultService.postCommonSum({ numbers });
    if (generalUtil.isError(returnVal)) {
      console.log(returnVal.error);
      return 0;
    } else if (returnVal.result === undefined) {
      return 0;
    }
    return returnVal.result;
  } catch (e) {
    console.log(e);
    return 0;
  }
};

const pageLoad = async () => {
  try {
    const returnVal = await DefaultService.getCommonHealth();
    if (generalUtil.isError(returnVal)) {
      console.log(returnVal.error);
      return 'Not OK';
    } else if (returnVal.status === undefined) {
      return 'Not OK';
    }
    return 'OK';
  } catch (e) {
    console.log(e);
    return 'Not OK';
  }
};

const helper = {
  handleCalculatorClick_Client,
  handleCalculatorClick_Server,
  pageLoad,
};

export default helper;
