import { structs_ErrorResponse } from '../api-autogenerated';

function isError(response: any): response is structs_ErrorResponse {
  return (response as structs_ErrorResponse).error !== undefined;
}

const generalUtil = {
  isError,
};
export default generalUtil;
